apiVersion: v1
kind: Service
metadata:
  name: blog-django-service
spec:
  type: NodePort
  selector:
    app: blog-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
